# Generated by Django 3.1.3 on 2020-11-21 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasker', '0002_tasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='checked',
            field=models.BooleanField(default=False),
        ),
    ]
