# Generated by Django 3.1.3 on 2020-11-25 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tasker', '0004_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='URL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('links', models.URLField()),
                ('subject', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Tasker.subject')),
            ],
        ),
    ]
