# Generated by Django 3.1.3 on 2020-11-25 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasker', '0006_auto_20201125_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='category',
            field=models.CharField(default=None, max_length=64, null=True),
        ),
    ]
