# Generated by Django 3.1.3 on 2020-11-25 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasker', '0007_subject_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='links',
            field=models.URLField(default=None, null=True),
        ),
    ]
