# Generated by Django 3.1.3 on 2020-11-25 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasker', '0008_auto_20201125_1557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='url',
            name='subject',
        ),
        migrations.AddField(
            model_name='subject',
            name='links',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='all_links', to='Tasker.URL'),
        ),
    ]
