# Generated by Django 3.1.3 on 2020-11-28 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasker', '0011_url_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='subject',
            field=models.CharField(max_length=200),
        ),
    ]
