# Generated by Django 3.1.3 on 2020-11-30 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasker', '0014_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='subject',
            field=models.CharField(max_length=200),
        ),
    ]
