# Generated by Django 3.1.3 on 2020-12-01 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasker', '0015_auto_20201130_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='links',
            field=models.URLField(null=True),
        ),
    ]
