# Generated by Django 3.1.3 on 2020-12-01 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasker', '0017_auto_20201201_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='links',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='url',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
