# Generated by Django 3.1.3 on 2020-12-01 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasker', '0018_auto_20201201_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='links',
            field=models.URLField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='url',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=200),
        ),
    ]
