# Generated by Django 3.1.3 on 2020-12-01 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasker', '0019_auto_20201201_2034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='tasks',
            name='deadline',
            field=models.DateField(null=True),
        ),
    ]
