# Generated by Django 3.1.3 on 2020-12-02 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasker', '0020_auto_20201201_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='deadline',
            field=models.DateField(null=True),
        ),
    ]
