name: CI
on: push

jobs:
  test_project:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run Selenium unit tests
      run: |
        pip3 install --user selenium
        python3 manage.py test