name: CI
on: push

jobs:
  test_project:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run Selenium unit test
      run: |
        pip3 install --user selenium
        pip3 install --user webdriver-manager
        pip3 install --user django
        python3 manage.py test